import { Valkey } from "iovalkey";
import { SpanStatusCode } from "@opentelemetry/api";
import { env } from "./env.js";
import { tracer } from "./telemetry.js";
import { valkeyCommandsTotal, valkeyErrorsTotal } from "./metrics.js";

// Valkey is back, but in a different role than the one it lost. It used to *hold* custom
// sample audio — the only copy, which is why it had a 5MB cap and why losing it lost data;
// storage.ts owns those bytes now. Here it holds only things whose loss is a re-derivation
// rather than a deletion: cross-instance presence (regenerated by the next heartbeat) and
// buffered autosaves (whose durable copy is Postgres). Nothing in this file is a system of
// record, which is what makes the degrade-to-nothing behavior below acceptable.
//
// "iovalkey" is the Valkey-maintained fork of ioredis; it understands `valkey://`,
// `valkeys://`, `redis://` and `rediss://` URLs, and turns TLS on automatically for the
// two `s` schemes — so an Aiven for Valkey URI works as-is with no extra config.
const client = new Valkey(env.valkeyUrl, {
  // The whole point of this layer is that it's optional. ioredis defaults to buffering
  // commands while disconnected and replaying them on reconnect, which would turn "Valkey
  // is down" into "every presence lookup and autosave hangs, then fires late" — the
  // opposite of what a cache should do. Failing the command immediately lets withValkey()
  // below fall through to the Postgres/in-memory path on the very first attempt.
  enableOfflineQueue: false,
  // Connect on demand rather than in the constructor, so importing this module can't emit
  // connection errors before connectValkey() has installed the error handler below.
  lazyConnect: true,
  // Same reasoning as kafka.ts's retry config: a local container may not be up yet right
  // after `docker compose up`, and a client that gives up retrying leaves the feature
  // permanently degraded until the gateway is manually restarted.
  retryStrategy: (times) => Math.min(times * 200, 10_000),
});

let ready = false;

// ioredis emits 'error' on every single failed reconnect attempt. Unhandled, that's a
// crash; logged verbatim, it's a line every few seconds forever when Valkey isn't running,
// which buries everything else. Log the first one and then at most one per minute.
let lastErrorLoggedAt = 0;
client.on("error", (err: Error) => {
  const now = Date.now();
  if (now - lastErrorLoggedAt < 60_000) return;
  lastErrorLoggedAt = now;
  console.warn(`valkey unavailable (presence + autosave buffering degraded): ${err.message}`);
});
client.on("ready", () => {
  ready = true;
  console.log(`valkey: connected (${env.valkeyUrl.replace(/\/\/[^@]*@/, "//***@")})`);
});
client.on("end", () => {
  ready = false;
});

/**
 * Tries to connect, but never throws — an unreachable Valkey degrades the two features
 * that use it (see withValkey) instead of stopping the gateway from starting at all.
 */
export async function connectValkey() {
  try {
    await client.connect();
  } catch (err) {
    console.warn(
      `valkey: couldn't connect at startup, continuing without it — ${
        err instanceof Error ? err.message : err
      }`,
    );
  }
}

export async function disconnectValkey() {
  // quit() waits for in-flight commands (the final autosave flush in particular) instead
  // of severing the socket the way disconnect() does.
  await client.quit().catch(() => client.disconnect());
}

/**
 * Runs `fn` against Valkey, returning `fallback` if Valkey is unreachable or the command
 * fails. Every caller in presence.ts/autosaveBuffer.ts goes through this, so there's
 * exactly one place that decides what "Valkey is down" means: quietly do the lesser thing.
 *
 * Spans are manual here for the same reason they are in db.ts/kafka.ts/storage.ts — the
 * bundled ioredis instrumentation hooks module load in a way that doesn't fire under Bun
 * (see telemetry.ts).
 */
export async function withValkey<T>(
  operation: string,
  fn: (client: Valkey) => Promise<T>,
  fallback: T,
): Promise<T> {
  if (!ready) return fallback;
  return tracer.startActiveSpan(`valkey.${operation}`, async (span) => {
    // "redis" rather than "valkey": the OTel semconv db.system registry has no valkey
    // value yet, and Valkey speaks the Redis protocol — same call as storage.ts making an
    // S3 request look like `rpc.system: aws-api`.
    span.setAttribute("db.system", "redis");
    span.setAttribute("db.operation", operation);
    try {
      const result = await fn(client);
      valkeyCommandsTotal.inc({ operation });
      return result;
    } catch (err) {
      span.recordException(err as Error);
      span.setStatus({ code: SpanStatusCode.ERROR, message: (err as Error).message });
      valkeyErrorsTotal.inc({ operation });
      console.error(`valkey ${operation} failed, falling back`, err);
      return fallback;
    } finally {
      span.end();
    }
  });
}

/** Whether Valkey is currently usable — for callers that need to pick a whole strategy, not just a value. */
export function isValkeyReady() {
  return ready;
}
