// Generates apps/gateway/src/chat/strudelApi.json — the bot's source of truth for what
// Strudel can actually do.
//
// Why this exists: the bot writes code into a buffer everyone in the room is looking at,
// and a model with no way to check whether a function exists will invent one. Watching a
// 9B local model produce `beat(30, 4)`, `loop(...)` and `wait(2)` is what prompted this —
// each parses as JavaScript and then throws for every person in the room.
//
// The names come from the *installed* @strudel packages rather than a scrape of
// strudel.cc, so they always describe the version this repo actually runs. Two passes:
//
//   1. Runtime. Import each source module and enumerate its exported functions, plus
//      Pattern.prototype for the method-chain vocabulary. This is authoritative and
//      catches the hundreds of names generated by register()/registerControl(), which no
//      static parse could see.
//   2. JSDoc. Parse the same files for descriptions, synonyms and examples. Strudel ships
//      its sources with docs intact, so this is the same text that builds strudel.cc.
//
// Pass 1 answers "does this exist"; pass 2 answers "what is it for". A name with no
// JSDoc is still a real function and still listed.
//
// Regenerate after upgrading @strudel/*:  bun run build:strudel-api

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

// @strudel/core's barrel pulls in @kabelsalat/web, whose published dist does not export
// the SalatRepl its importer asks for — importing @strudel/core by name throws before any
// of this can run. The dependency is for a feature nothing here uses, so it is stubbed
// rather than worked around; every module below then loads normally.
Bun.plugin({
  name: "kabelsalat-stub",
  setup(build) {
    build.module("@kabelsalat/web", () => ({
      loader: "js",
      contents: "export class SalatRepl {}; export default {};",
    }));
  },
});

/** Source modules to read, in the order their names should win ties. */
const MODULES: Array<{ package: string; files: string[] }> = [
  {
    package: "@strudel/core",
    files: ["pattern.mjs", "signal.mjs", "controls.mjs", "euclid.mjs", "pick.mjs", "speak.mjs"],
  },
  { package: "@strudel/mini", files: ["mini.mjs"] },
  { package: "@strudel/tonal", files: ["tonal.mjs", "voicings.mjs"] },
  { package: "@strudel/webaudio", files: ["webaudio.mjs"] },
  { package: "@strudel/draw", files: ["draw.mjs"] },
];

/**
 * Free functions the REPL provides that live in no package source — they're injected by
 * the transpiler or the web wrapper, so neither pass above can see them, and leaving them
 * out would have the validator reject correct code.
 */
const REPL_GLOBALS: Record<string, string> = {
  setcpm: "Sets the tempo in cycles per minute. One cycle is a bar, so 120bpm in 4/4 is setcpm(30).",
  setcps: "Sets the tempo in cycles per second. setcpm(n) is setcps(n/60).",
  samples: "Loads a sample map or sample bank so its names can be used with s().",
  hush: "Stops everything that is playing.",
  all: "Applies a function to every active pattern at once.",
  silence: "A pattern that plays nothing.",
};

/** JavaScript builtins a pattern legitimately reaches for. Not Strudel, but not a mistake. */
const JS_GLOBALS = ["Math", "Number", "String", "Array", "Object", "JSON", "Boolean", "parseInt", "parseFloat", "Date"];

export interface StrudelFunction {
  name: string;
  /** `free` is callable as `name(...)`; `method` only as `.name(...)` in a chain. */
  kind: "free" | "method";
  source: string;
  description?: string;
  synonyms?: string[];
  examples?: string[];
  /**
   * Exact number of arguments this method requires, when Strudel enforces one. Absent means
   * any number is accepted. See probeRequiredArgs — this is measured, not guessed.
   */
  requiredArgs?: number;
  /**
   * True when calling this method with no arguments silences the pattern outright. See
   * probeSilencing — also measured, because nothing in the signature says so.
   */
  silentWithNoArgs?: boolean;
  /**
   * Argument positions that must be a *function* rather than a value. See
   * probeFunctionArgs — measured, because Strudel barely documents this and the failure is
   * `e is not a function` from inside a minified bundle.
   */
  functionArgs?: number[];
}

// ── pass 1: what exists ──────────────────────────────────────────────────────────────

const free = new Map<string, string>(); // name -> package
const methods = new Map<string, string>();

// The barrel is imported first and on purpose. @strudel/tonal, /draw and /webaudio all
// import `@strudel/core` by name, while importing `@strudel/core/pattern.mjs` directly
// yields a *second, separate* Pattern class (this is what @strudel/core's own "loaded more
// than once" warning is about). Register onto one and read from the other and .scale, .chord
// and every control silently go missing — which is how 700 of 943 chain methods were absent
// from an index that still looked plausible.
await import("@strudel/core");

for (const { package: pkg, files } of MODULES) {
  for (const file of files) {
    const specifier = `${pkg}/${file}`;
    let mod: Record<string, unknown>;
    try {
      mod = (await import(specifier)) as Record<string, unknown>;
    } catch (err) {
      // Loud, not fatal: a module that stops loading after an upgrade should be visible
      // in the build output rather than silently shrinking the bot's vocabulary.
      console.warn(`  ! skipped ${specifier}: ${err instanceof Error ? err.message.split("\n")[0] : err}`);
      continue;
    }
    for (const [name, value] of Object.entries(mod)) {
      if (typeof value === "function" && /^[a-z_$]/i.test(name) && !free.has(name)) free.set(name, pkg);
    }
    // Pattern.prototype is deliberately NOT read here — see the pass below.
  }
}

// Pattern.prototype must be read *after* every module above has been imported, not while
// looping over them. register() and registerControl() add to it as a side effect of import,
// so a snapshot taken during the first module misses everything the later ones install —
// which is exactly what happened: .gain, .room, .lpf, .note and 400-odd other controls were
// absent from the index because controls.mjs had not run yet. The symptom was silent (a
// shorter list is still a plausible-looking list), and it is why `sound.partial(...)` could
// not be caught: with a third of the vocabulary missing, checking method names at all would
// have rejected `.gain()`.
const barrel = (await import("@strudel/core")) as {
  Pattern: { prototype: object };
  pure(value: unknown): unknown;
  sequence(...values: unknown[]): unknown;
};

for (const name of Object.getOwnPropertyNames(barrel.Pattern.prototype)) {
  if (name === "constructor" || name.startsWith("_")) continue;
  if (!methods.has(name)) methods.set(name, "@strudel/core");
}

/**
 * Chain methods installed at *runtime* by the REPL rather than by importing a package, so
 * nothing above can see them. Small and explicit, like REPL_GLOBALS — the cost of missing
 * one is that correct code gets warned about, which is the failure this file exists to avoid.
 */
const RUNTIME_METHODS: Record<string, string> = {
  p: "Registers a pattern under a label so several can play at once. `$:` compiles to this.",
  pianoroll: "Draws the pattern as a piano roll (@strudel/draw, registered by the REPL).",
  punchcard: "Draws the pattern as a punchcard (@strudel/draw, registered by the REPL).",
};

// ── pass 1b: how many arguments each method demands ─────────────────────────────────

/**
 * The number of arguments a chained method requires, or null when any number will do.
 *
 * Measured by calling it, rather than read off the source, because Strudel's rule is a
 * property of register() rather than of the function's signature (pattern.mjs):
 *
 *   if (arity === 2 && args.length !== 1) { args = [sequence(...args)]; }
 *   else if (arity !== args.length + 1) { throw `.${name}() expects ${arity - 1} inputs` }
 *
 * So arity-2 functions swallow *any* number of arguments — `.fast()`, `.fast(2)` and
 * `.fast(2,3)` are all fine — while everything else demands exactly one number of them.
 * `.every(2)` throws and `.room()` does not, and no reading of their parameter lists
 * predicts that. Probing with 0 then 1 arguments makes Strudel state its own requirement in
 * the error message, which is the only source that can't drift.
 */
function probeRequiredArgs(method: (...args: unknown[]) => unknown, pattern: () => unknown): number | null {
  for (const args of [[], [one]]) {
    try {
      method.apply(pattern(), args);
    } catch (err) {
      const match = /expects (\d+) inputs/.exec(String((err as Error)?.message ?? ""));
      if (match) return Number(match[1]);
    }
  }
  return null;
}

/**
 * Whether calling a method with no arguments silences the pattern.
 *
 * register() folds a zero-argument call on an arity-2 method into `sequence()` — which is
 * silence — so `s("bd hh").fast()` and `s("bd hh").jux()` query to *zero events*. Strudel
 * raises nothing: the pattern is simply inaudible, which is the same failure as a bad sample
 * name and just as hard to see from inside a room. Meanwhile `.room()` and `.gain()` with no
 * arguments are harmless. Only measuring tells them apart.
 */
function probeSilencing(method: (...args: unknown[]) => unknown, pattern: () => { queryArc(a: number, b: number): unknown[] }): boolean {
  try {
    if (pattern().queryArc(0, 1).length === 0) return false; // baseline is already silent
    const result = method.apply(pattern(), []) as { queryArc(a: number, b: number): unknown[] };
    return result?.queryArc?.(0, 1).length === 0;
  } catch {
    return false;
  }
}

/**
 * Which argument positions have to be a function.
 *
 * `.every(16, 3)` throws `e is not a function. (In 'e(n)', 'e' is 3)` — from inside a
 * minified bundle, so the name in the message is meaningless and the line number points at
 * Strudel rather than at the pattern. `.every(16, rev)` is fine. Nothing in the docs says
 * which argument is which: only 15 params in all of pattern.mjs carry a JSDoc `{Function}`
 * type, and `every` is not one of them.
 *
 * So it is measured — and the question has to be asked precisely, because two obvious
 * phrasings both give wrong answers:
 *
 *   "does a function here remove the error?"   -> `every` needs one in both positions.
 *      A function in the count position breaks it *differently*, and different reads as
 *      fixed. Gating on that would reject `every(16, rev)`.
 *   "does a number here reintroduce the error?" -> `every` needs one nowhere.
 *      With functions in every position it is already broken, so nothing stands out.
 *
 * What actually identifies the position is whether the call *works*: a function there, plain
 * numbers everywhere else, and real events come out.
 */
function probeFunctionArgs(
  method: (...args: unknown[]) => unknown,
  pattern: () => unknown,
  count: number,
): number[] {
  const identity = (pat: unknown) => pat;

  const outcome = (args: unknown[]): "works" | "not-a-function" | "other" => {
    try {
      const result = method.apply(pattern(), args) as { queryArc(a: number, b: number): unknown[] };
      return (result?.queryArc?.(0, 1)?.length ?? 0) > 0 ? "works" : "other";
    } catch (err) {
      return /is not a function/.test(String((err as Error)?.message ?? "")) ? "not-a-function" : "other";
    }
  };

  const numbers = () => Array.from({ length: count }, () => 1 as unknown);
  if (outcome(numbers()) !== "not-a-function") return [];

  const positions: number[] = [];
  for (let index = 0; index < count; index++) {
    const args = numbers();
    args[index] = identity;
    if (outcome(args) === "works") positions.push(index);
  }
  return positions;
}

const requiredArgs = new Map<string, number>();
const functionArgs = new Map<string, number[]>();
const silencing = new Set<string>();
let one: unknown;

{
  const core = barrel;
  one = core.pure(1);
  const proto = core.Pattern.prototype;
  for (const name of Object.getOwnPropertyNames(proto)) {
    if (name === "constructor" || name.startsWith("_")) continue;
    // Property *access* runs a getter, and several of these are getters that throw off a
    // bare pattern — so go through the descriptor and only probe real methods.
    const descriptor = Object.getOwnPropertyDescriptor(proto, name);
    if (!descriptor || typeof descriptor.value !== "function") continue;
    try {
      const required = probeRequiredArgs(descriptor.value, () => core.pure("bd"));
      if (required !== null) requiredArgs.set(name, required);
      // Only meaningful where a zero-argument call is even allowed.
      else if (probeSilencing(descriptor.value, () => core.sequence("bd", "hh") as never)) silencing.add(name);

      // Arity-2 methods take any number of arguments, so probe them at one; the rest at
      // exactly what they demand.
      const positions = probeFunctionArgs(descriptor.value, () => core.pure("bd"), required ?? 1);
      if (positions.length > 0) functionArgs.set(name, positions);
    } catch {
      // A method that fails for some other reason simply gets no arity recorded, which
      // means "don't check it" downstream — the safe direction.
    }
  }
}

// ── pass 2: what it's for ────────────────────────────────────────────────────────────

interface Doc {
  description?: string;
  synonyms?: string[];
  examples: string[];
}
const docs = new Map<string, Doc>();

/** Trims a JSDoc block's leading ` * ` decoration. */
function undecorate(block: string): string[] {
  return block.split("\n").map((line) => line.replace(/^\s*\*ap?/, "").replace(/^\s*\*/, "").replace(/^ /, ""));
}

for (const { package: pkg, files } of MODULES) {
  for (const file of files) {
    let source: string;
    try {
      source = readFileSync(resolve("node_modules", pkg, file), "utf8");
    } catch {
      continue;
    }

    // Each JSDoc block plus whatever declaration follows it, which is where the name is
    // when there's no @name tag.
    for (const match of source.matchAll(/\/\*\*([\s\S]*?)\*\/\s*([^\n]*)/g)) {
      const lines = undecorate(match[1]);
      const after = match[2];

      const prose: string[] = [];
      const examples: string[] = [];
      let synonyms: string[] | undefined;
      let explicitName: string | undefined;
      let current: string[] | null = prose;

      for (const line of lines) {
        const tag = line.match(/^\s*@(\w+)\s*(.*)$/);
        if (tag) {
          const [, name, rest] = tag;
          if (name === "name") explicitName = rest.trim();
          else if (name === "synonyms") synonyms = rest.split(",").map((s) => s.trim()).filter(Boolean);
          else if (name === "example") {
            examples.push("");
            current = null;
          } else current = null;
          if (name === "example") current = examples;
          continue;
        }
        if (current === prose) prose.push(line);
        else if (current === examples && examples.length > 0) {
          examples[examples.length - 1] += `${line}\n`;
        }
      }

      // Name resolution, most explicit first. register('x') and register(['x','alias'])
      // are how most of Strudel declares itself, so they outrank the `export const` name
      // (which is often a wrapper with a different identifier).
      const registered = after.match(/register\(\s*\[?\s*['"]([^'"]+)['"]/);
      const declared = after.match(/^export\s+(?:const|function|let)\s+([A-Za-z_$][\w$]*)/);
      const destructured = after.match(/^export\s+const\s*\{\s*([A-Za-z_$][\w$]*)/);
      const name = explicitName || registered?.[1] || declared?.[1] || destructured?.[1];
      if (!name) continue;

      const description = prose.join("\n").trim().replace(/\s+/g, " ") || undefined;
      const cleaned = examples.map((e) => e.trim()).filter(Boolean).slice(0, 2);
      if (!description && cleaned.length === 0) continue;
      if (!docs.has(name)) docs.set(name, { description, synonyms, examples: cleaned });
    }
  }
}

// ── merge ────────────────────────────────────────────────────────────────────────────

const functions: StrudelFunction[] = [];
const seen = new Set<string>();

function add(name: string, kind: "free" | "method", source: string, fallback?: string) {
  if (seen.has(`${kind}:${name}`)) return;
  seen.add(`${kind}:${name}`);
  const doc = docs.get(name);
  functions.push({
    name,
    kind,
    source,
    ...(kind === "method" && requiredArgs.has(name) ? { requiredArgs: requiredArgs.get(name) } : {}),
    ...(kind === "method" && silencing.has(name) ? { silentWithNoArgs: true } : {}),
    ...(kind === "method" && functionArgs.has(name) ? { functionArgs: functionArgs.get(name) } : {}),
    description: doc?.description ?? fallback,
    ...(doc?.synonyms?.length ? { synonyms: doc.synonyms } : {}),
    ...(doc?.examples.length ? { examples: doc.examples } : {}),
  });
}

for (const [name, pkg] of free) add(name, "free", pkg);
for (const [name, description] of Object.entries(REPL_GLOBALS)) add(name, "free", "repl", description);
for (const [name, description] of Object.entries(RUNTIME_METHODS)) add(name, "method", "repl", description);
for (const name of JS_GLOBALS) add(name, "free", "javascript");
for (const [name, pkg] of methods) add(name, "method", pkg);

functions.sort((a, b) => a.name.localeCompare(b.name) || a.kind.localeCompare(b.kind));

const versions: Record<string, string> = {};
for (const { package: pkg } of MODULES) {
  try {
    versions[pkg] = JSON.parse(readFileSync(resolve("node_modules", pkg, "package.json"), "utf8")).version;
  } catch {
    /* not installed; the skip above already said so */
  }
}

const out = resolve("apps/gateway/src/chat/strudelApi.json");
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, `${JSON.stringify({ versions, functions }, null, 1)}\n`);

const documented = functions.filter((f) => f.description).length;
console.log(
  `wrote ${out}\n  ${functions.length} names (${functions.filter((f) => f.kind === "free").length} free, ` +
    `${functions.filter((f) => f.kind === "method").length} chainable), ${documented} documented, ` +
    `${functions.filter((f) => f.examples).length} with examples`,
);
